project:
  type: website
  resources: "Kevin_Ngo_Resume.pdf"

website:
  title: "Kevin Ngo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Projects.qmd
        text: Projects
      
  page-footer: 
    right: "&copy; 2025, Kevin Ngo"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


execute:
 freeze: auto

